package one.captl.RESTful.notification.model.enums;

public enum InfoFieldType {
    FundName,
    FundRegistrationNo,
    FundAddressLine1,
    FundAddressLine2,
    FundZip,
    FundState,
    FundCity,
    FundCountry,
    FundContinent,
    FundCorpus,
    FundVintage,
    FundTeam,
    FundTrustees,
    FundLawFirms,
    FundAuditFirms,
    FundValuationFirms,
    FundBanks,

    LPAddressLine1,
    LPAddressLine2,
    LPZip,
    LPState,
    LPCity,
    LPCountry,
    LPContinent,
    LPName,
    LPTeam,
    LPAuditFirms,
    LPLawFirms,

    PortfolioName,
    PortfolioAddressLine1,
    PortfolioAddressLine2,
    PortfolioZip,
    PortfolioState,
    PortfolioCity,
    PortfolioCountry,
    PortfolioContinent,

    PortfolioIndustryVertical,
    PortfolioMembers,
    PortfolioLawFirms,
    PortfolioAuditFirms,
    PortfolioBanks
}
